USE OMNIKNOW;

CREATE TABLE ESTADOS_REPORTES(
	ID_ESTADO_REPORTE INTEGER(10),
    NOMBRE VARCHAR(50),
    PRIMARY KEY(ID_ESTADO_REPORTE)
);
INSERT INTO ESTADOS_REPORTES VALUES(1, 'Pendiente');
INSERT INTO ESTADOS_REPORTES VALUES(2, 'Resuelto');
INSERT INTO ESTADOS_REPORTES VALUES(3, 'Cerrado');
INSERT INTO ESTADOS_REPORTES VALUES(4, 'Pagado');

CREATE TABLE TIPOS_MANTENIMIENTOS(
	ID_TIPO_MANTENIMIENTO INTEGER(10),
    NOMBRE VARCHAR(50),
    PRIMARY KEY(ID_TIPO_MANTENIMIENTO)
);
INSERT INTO TIPOS_MANTENIMIENTOS VALUES(1,'Preventivo');
INSERT INTO TIPOS_MANTENIMIENTOS VALUES(2,'Correctivo');
INSERT INTO TIPOS_MANTENIMIENTOS VALUES(3,'Adaptativo');
INSERT INTO TIPOS_MANTENIMIENTOS VALUES(4,'Perfecto');

CREATE TABLE USUARIOS(
	ID_USUARIO INTEGER(10),
    USUARIO VARCHAR(50),
    CONTRASENA VARCHAR(50),
    NOMBRE VARCHAR(100),
    TIPO INTEGER(2),
    INICIADO TINYINT,
    PRIMARY KEY(ID_USUARIO)
);

CREATE TABLE REPORTES_MANTENIMIENTOS(
	ID_REPORTE_MANTENIMIENTO INTEGER(10),
    ID_REPORTE_EVENTO INTEGER(10),
    ID_ESTADO_REPORTE INTEGER(10),
    ID_TIPO_MANTENIMIENTO INTEGER(10),
    ID_USUARIO INTEGER(10),
    FECHA DATETIME,
    ASUNTO TEXT,
    DESCRIPCION TEXT,
    SOLUCION TEXT,
    PRIMARY KEY(ID_REPORTE_MANTENIMIENTO),
    FOREIGN KEY(ID_ESTADO_REPORTE) REFERENCES ESTADOS_REPORTES(ID_ESTADO_REPORTE),
    FOREIGN KEY(ID_TIPO_MANTENIMIENTO) REFERENCES TIPOS_MANTENIMIENTOS(ID_TIPO_MANTENIMIENTO),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);